In [5]:
import torch
from torch import nn
from torch.nn import functional as F

In [36]:
n_item = 10
n_feature = 2

torch.manual_seed(123)
data_x = torch.randn(size=(n_item, n_feature)).float()
data_y = torch.where(
    torch.subtract(data_x[:, 0] * 0.5, data_x[:, 1] * 1.5) + 0.02 > 0, 0, 1
).long()

data_y = F.one_hot(data_y)


In [37]:


class BinaryClassificationModael(nn.Module):
    def __init__(self,in_feature):
        super(BinaryClassificationModael,self).__init__()
        #  single perceptron
        # self.layer_1 = nn.Linear(in_features = in_feature,out_features=2, bias=True)
        # mult1 perceptron
        self.layer_1 = nn.Linear(in_features = in_feature,out_features=128, bias=True)
        self.layer_2 = nn.Linear(in_features = 128,out_features=512, bias=True)
        self.layer_final = nn.Linear(in_features = 512,out_features=2, bias=True)
        
    def forward(self, x):
        print(x)
        # return F.sigmoid(self.layer_1(x))
        layer_1_output = F.sigmoid(self.layer_1(x))
        layer_2_output = F.sigmoid(self.layer_2(layer_1_output))
        layer_final_output = F.sigmoid(self.layer_final(layer_2_output))
        return layer_final_output

In [39]:
learning_rate = 0.01
epoch = 100
model = BinaryClassificationModael(n_feature)
opt = torch.optim.SGD(model.parameters(), lr=learning_rate)

criteria =  nn.BCELoss()

for epoch in range(1000):
    for step in range(n_item):
        x = data_x[step]
        y = data_y[step]
        opt.zero_grad()
        y_hat = model(x.unsqueeze(0))
        loss = criteria(y_hat, y.unsqueeze(0).float())
        loss.backward()
        opt.step()
    print(f'epoch: {epoch}, loss: {loss.item()}')

tensor([[ 0.3374, -0.1778]])
tensor([[-0.3035, -0.5880]])
tensor([[1.5810, 1.3010]])
tensor([[ 1.2753, -0.2010]])
tensor([[-0.1606, -0.4015]])
tensor([[ 0.6957, -1.8061]])
tensor([[-1.1589,  0.3255]])
tensor([[-0.6315, -2.8400]])
tensor([[-0.7849, -1.4096]])
tensor([[-0.4076,  0.7953]])
epoch: 0, loss: 1.2836658954620361
tensor([[ 0.3374, -0.1778]])
tensor([[-0.3035, -0.5880]])
tensor([[1.5810, 1.3010]])
tensor([[ 1.2753, -0.2010]])
tensor([[-0.1606, -0.4015]])
tensor([[ 0.6957, -1.8061]])
tensor([[-1.1589,  0.3255]])
tensor([[-0.6315, -2.8400]])
tensor([[-0.7849, -1.4096]])
tensor([[-0.4076,  0.7953]])
epoch: 1, loss: 1.3523801565170288
tensor([[ 0.3374, -0.1778]])
tensor([[-0.3035, -0.5880]])
tensor([[1.5810, 1.3010]])
tensor([[ 1.2753, -0.2010]])
tensor([[-0.1606, -0.4015]])
tensor([[ 0.6957, -1.8061]])
tensor([[-1.1589,  0.3255]])
tensor([[-0.6315, -2.8400]])
tensor([[-0.7849, -1.4096]])
tensor([[-0.4076,  0.7953]])
epoch: 2, loss: 1.365990161895752
tensor([[ 0.3374, -0.1778]])
ten

KeyboardInterrupt: 