In [2]:
import torch
import torch.nn as nn
import unittest
def test_linear():
    input_dim = 5
    output_dim = 3
    linear_layer = nn.Linear(input_dim, output_dim)
    print(linear_layer)
    

    # Create a random tensor of size (10, input_dim)
    x = torch.randn(10, input_dim)
    y = linear_layer(x)

    # Check the output size
    
test_linear()

Linear(in_features=5, out_features=3, bias=True)


In [31]:
# torch.manual_seed(1) # Set the seed for reproducibility
input_tensor = torch.randn(10, 3)
model = nn.Linear(3, 3)
print(model.weight)
print(model.bias)

output_tensor = model(input_tensor)

print(output_tensor)
torch.save(model.state_dict(), 'model_parameters.pth')


Parameter containing:
tensor([[-0.1291,  0.4065, -0.1172],
        [ 0.5210,  0.4544, -0.2069],
        [ 0.0207, -0.2521, -0.2335]], requires_grad=True)
Parameter containing:
tensor([-0.1169, -0.0039, -0.2013], requires_grad=True)
tensor([[ 0.4568,  0.5242, -0.2667],
        [-0.2656,  0.7965, -0.0910],
        [ 0.9250,  0.9598, -0.2066],
        [ 0.3152,  0.0433,  0.1815],
        [-0.2664, -1.1922, -0.3716],
        [-0.3210, -0.5586,  0.1395],
        [-1.0068, -0.4379,  0.0925],
        [-0.4052,  0.8033,  0.1362],
        [ 0.5862,  0.5748, -0.2996],
        [-0.5401, -1.0316,  0.1651]], grad_fn=<AddmmBackward0>)


In [34]:
import torch
import pandas as pd
model_state_dict = torch.load('model_parameters.pth')
# 将参数转换为 pandas DataFrame
# 将权重和偏置分别转换为 pandas DataFrame
weights_data = {"param": model_state_dict[param_tensor].numpy() for param_tensor in model_state_dict if 'weight' in param_tensor}
biases_data = {"param": model_state_dict[param_tensor].numpy() for param_tensor in model_state_dict if 'bias' in param_tensor}

weights_df = pd.DataFrame({k: v.flatten() for k, v in weights_data.items()})
biases_df = pd.DataFrame({k: v.flatten() for k, v in biases_data.items()})

# 查看权重表格
print("Weights DataFrame:")
display(weights_df.head())

# 查看偏置表格
print("Biases DataFrame:")
display(biases_df.head())

Weights DataFrame:


param
0 -0.129126
1  0.406513
2 -0.117249
3  0.521018
4  0.454430

Biases DataFrame:


param
0 -0.116895
1 -0.003936
2 -0.201260

In [2]:
import torch

x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Original matrix:")
print(x)

# 转置矩阵
x_transposed = x.transpose(0, 1)
print("\nTransposed matrix:")
print(x_transposed)

Original matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])

Transposed matrix:
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [24]:
import torch
embeddings = torch.randn(1, 2, 4)  # 64 个句子，每个句子 100 个词，每个词嵌入到 300 维向量
print("Original embeddings tensor:")
print(embeddings)
print(embeddings.shape)

scalar = torch.tensor(5)
print(f'Scalar: {scalar.shape}')
vector = torch.tensor([1, 2, 3])
print(f'Vector: {vector}')
print(f'Vector: {vector.shape}')
vector = torch.randn(2,3)
print(f'Vector: {vector}')
print(f'Vector: {vector.shape}')




Original embeddings tensor:
tensor([[[ 1.2070,  0.1724, -1.4187,  1.0755],
         [ 0.2303,  0.1073,  0.2291,  0.2149]]])
torch.Size([1, 2, 4])
Scalar: torch.Size([])
Vector: tensor([1, 2, 3])
Vector: torch.Size([3])
Vector: tensor([[-0.4925, -2.2336, -0.4271],
        [-2.1664, -0.8761, -0.9369]])
Vector: torch.Size([2, 3])


In [37]:
import torch

tensor_3d = torch.tensor([
    [
        [1.1, 1.2, 1.3, 1.4],
        [2.1, 2.2, 2.3, 2.4]
    ]
])
print(tensor_3d.shape)
print(tensor_3d)
tran = tensor_3d.transpose(1,2)
print(tran.shape)
print(tran)


torch.Size([1, 2, 4])
tensor([[[1.1000, 1.2000, 1.3000, 1.4000],
         [2.1000, 2.2000, 2.3000, 2.4000]]])
torch.Size([1, 4, 2])
tensor([[[1.1000, 2.1000],
         [1.2000, 2.2000],
         [1.3000, 2.3000],
         [1.4000, 2.4000]]])


In [23]:
import torch
import torch.nn as nn

class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, head):
        super(MultiHeadAttention, self).__init__()
        self.d_model = d_model
        self.head = head
        self.d_k = d_model // head
        self.linear_query = nn.Linear(d_model, d_model)

    def forward(self, query):
        n_batch = query.size(0)
        
        # 线性变换并调整形状
        query = self.linear_query(query)
        print(f'query: {query.shape}')
        print(query)
        query = query.view(n_batch, -1, self.head, self.d_k).transpose(1, 2)
        
        return query

# 示例输入
d_model = 8
head = 8
seq_len = 2
n_batch = 2

query = torch.randn(n_batch, seq_len, d_model)
print(f'query: {query.shape}')
print(query)
attention_layer = MultiHeadAttention(d_model, head)

# 计算查询向量
query_transformed = attention_layer(query)
print(query_transformed)  # 输出形状：torch.Size([32, 8, 10, 64])


query: torch.Size([2, 2, 8])
tensor([[[ 0.8065, -0.3399, -1.1084,  0.5254,  1.8009, -1.2985,  0.3069,
          -1.0716],
         [ 0.0094, -0.8840, -0.2189, -0.4710,  0.2439, -0.7708,  0.3005,
           0.8937]],

        [[-0.2834, -0.3945, -1.9882, -0.4478,  1.2018,  1.3639, -0.6422,
          -0.3573],
         [ 0.1019, -0.8515, -0.7394,  0.6198, -0.1174, -1.2281,  0.5674,
          -0.9628]]])
query: torch.Size([2, 2, 8])
tensor([[[ 4.9903e-01, -1.2263e+00, -2.2188e-01,  7.1285e-01,  1.0389e+00,
           1.8268e+00, -4.6535e-01,  2.6636e-02],
         [ 6.4055e-01, -1.0461e-01, -2.9584e-01, -2.0339e-01,  5.7679e-01,
          -9.4181e-04, -1.5837e-01,  2.7724e-01]],

        [[-5.1174e-01, -7.1982e-01, -3.8112e-01,  1.2352e+00, -9.3439e-02,
           7.8247e-01, -2.3243e-01,  3.0152e-01],
         [ 3.5904e-01, -4.7988e-01,  3.9127e-02, -2.1624e-01,  6.7701e-01,
           9.3799e-01,  8.8460e-02,  1.4140e-01]]], grad_fn=<ViewBackward0>)
tensor([[[[ 4.9903e-01],
          [ 